### PR TITLE
Fix 32 bit php compatibility with permission bits

### PR DESCRIPTION
**Pull request by SQKo**
Added a new composer dependency https://github.com/brick/math
Added a new helper class **Bitwise.php**
Added missing permissions `manage_events` & `moderate_members`

Changed the permission constants back to hexadecimal form as doing bit shift left on bits above 31 on 32 bit php will give unexpected result due to integer overflow.
Note: this is only safe up to 44th bits, discord permission beyond 1 << 43 would require the constant value wrapped as numeric string (i.e. `1 << 44` = `'17592186044416'`)

Potentially breaking changes:

`$role->bitwise` now returns string instead of int for 32 bit PHP.

Fixed `Member::getPermissions()` returning all true when a member has permission with bits above 31 set.

Might need to be deeply tested (e.g. with combination of multiple permissions of roles and channels). 64 bit PHP should not be affected.

This fix is also applicable for v6.x since gateway API v8 is also affected.

Reference:
https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags

### Quick Test
Tested on the bot running DiscordPHP
`@everyone` has no permissions
The bot role has "View Channels" `view_channel`  (`1 << 10`) & "Use Application Commands" `use_slash_commands` (`1 << 31`) permission set

```php
$botmember = $message->channel->guild->members->offsetGet($discord->id);
var_dump($botmember);
$botperms = $botmember->getPermissions();
var_dump($botperms);
```

All irrelevant var_dump data is removed from the output below

Before:
```
object(Discord\Parts\Permissions\RolePermission)#1822 (41) {
  ["create_instant_invite"]=>
  bool(true)
  ["manage_channels"]=>
  bool(true)
  ["view_channel"]=>
  bool(true)
  ["manage_roles"]=>
  bool(true)
  ["manage_webhooks"]=>
  bool(true)
  ["add_reactions"]=>
  bool(true)
  ["send_messages"]=>
  bool(true)
  ["send_tts_messages"]=>
  bool(true)
  ["manage_messages"]=>
  bool(true)
  ["embed_links"]=>
  bool(true)
  ["attach_files"]=>
  bool(true)
  ["read_message_history"]=>
  bool(true)
  ["mention_everyone"]=>
  bool(true)
  ["use_external_emojis"]=>
  bool(true)
  ["use_slash_commands"]=>
  bool(false)
  ["manage_threads"]=>
  bool(true)
  ["use_public_threads"]=>
  bool(true)
  ["use_private_threads"]=>
  bool(true)
  ["use_external_stickers"]=>
  bool(true)
  ["send_messages_in_threads"]=>
  bool(true)
  ["priority_speaker"]=>
  bool(true)
  ["stream"]=>
  bool(true)
  ["connect"]=>
  bool(true)
  ["speak"]=>
  bool(true)
  ["mute_members"]=>
  bool(true)
  ["deafen_members"]=>
  bool(true)
  ["move_members"]=>
  bool(true)
  ["use_vad"]=>
  bool(true)
  ["request_to_speak"]=>
  bool(true)
  ["manage_events"]=>
  bool(true)
  ["start_embedded_activities"]=>
  bool(true)
  ["kick_members"]=>
  bool(true)
  ["ban_members"]=>
  bool(true)
  ["administrator"]=>
  bool(true)
  ["manage_guild"]=>
  bool(true)
  ["view_audit_log"]=>
  bool(true)
  ["view_guild_insights"]=>
  bool(true)
  ["change_nickname"]=>
  bool(true)
  ["manage_nicknames"]=>
  bool(true)
  ["manage_emojis"]=>
  bool(true)
  ["bitwise"]=>
  int(2147483647)
}

object(Discord\Parts\Permissions\RolePermission)#1870 (41) {
  ["create_instant_invite"]=>
  bool(true)
  ["manage_channels"]=>
  bool(true)
  ["view_channel"]=>
  bool(true)
  ["manage_roles"]=>
  bool(true)
  ["manage_webhooks"]=>
  bool(true)
  ["add_reactions"]=>
  bool(true)
  ["send_messages"]=>
  bool(true)
  ["send_tts_messages"]=>
  bool(true)
  ["manage_messages"]=>
  bool(true)
  ["embed_links"]=>
  bool(true)
  ["attach_files"]=>
  bool(true)
  ["read_message_history"]=>
  bool(true)
  ["mention_everyone"]=>
  bool(true)
  ["use_external_emojis"]=>
  bool(true)
  ["use_slash_commands"]=>
  bool(true)
  ["manage_threads"]=>
  bool(true)
  ["use_public_threads"]=>
  bool(true)
  ["use_private_threads"]=>
  bool(true)
  ["use_external_stickers"]=>
  bool(true)
  ["send_messages_in_threads"]=>
  bool(true)
  ["priority_speaker"]=>
  bool(true)
  ["stream"]=>
  bool(true)
  ["connect"]=>
  bool(true)
  ["speak"]=>
  bool(true)
  ["mute_members"]=>
  bool(true)
  ["deafen_members"]=>
  bool(true)
  ["move_members"]=>
  bool(true)
  ["use_vad"]=>
  bool(true)
  ["request_to_speak"]=>
  bool(true)
  ["manage_events"]=>
  bool(true)
  ["start_embedded_activities"]=>
  bool(true)
  ["kick_members"]=>
  bool(true)
  ["ban_members"]=>
  bool(true)
  ["administrator"]=>
  bool(true)
  ["manage_guild"]=>
  bool(true)
  ["view_audit_log"]=>
  bool(true)
  ["view_guild_insights"]=>
  bool(true)
  ["change_nickname"]=>
  bool(true)
  ["manage_nicknames"]=>
  bool(true)
  ["manage_emojis"]=>
  bool(true)
  ["bitwise"]=>
  int(-1)
}
```

After:
```
object(Discord\Parts\Permissions\RolePermission)#1822 (42) {
  ["create_instant_invite"]=>
  bool(false)
  ["manage_channels"]=>
  bool(false)
  ["view_channel"]=>
  bool(true)
  ["manage_roles"]=>
  bool(false)
  ["manage_webhooks"]=>
  bool(false)
  ["add_reactions"]=>
  bool(false)
  ["send_messages"]=>
  bool(false)
  ["send_tts_messages"]=>
  bool(false)
  ["manage_messages"]=>
  bool(false)
  ["embed_links"]=>
  bool(false)
  ["attach_files"]=>
  bool(false)
  ["read_message_history"]=>
  bool(false)
  ["mention_everyone"]=>
  bool(false)
  ["use_external_emojis"]=>
  bool(false)
  ["use_slash_commands"]=>
  bool(true)
  ["manage_threads"]=>
  bool(false)
  ["use_public_threads"]=>
  bool(false)
  ["use_private_threads"]=>
  bool(false)
  ["use_external_stickers"]=>
  bool(false)
  ["send_messages_in_threads"]=>
  bool(false)
  ["priority_speaker"]=>
  bool(false)
  ["stream"]=>
  bool(false)
  ["connect"]=>
  bool(false)
  ["speak"]=>
  bool(false)
  ["mute_members"]=>
  bool(false)
  ["deafen_members"]=>
  bool(false)
  ["move_members"]=>
  bool(false)
  ["use_vad"]=>
  bool(false)
  ["request_to_speak"]=>
  bool(false)
  ["manage_events"]=>
  bool(false)
  ["start_embedded_activities"]=>
  bool(false)
  ["kick_members"]=>
  bool(false)
  ["ban_members"]=>
  bool(false)
  ["administrator"]=>
  bool(false)
  ["manage_guild"]=>
  bool(false)
  ["view_audit_log"]=>
  bool(false)
  ["view_guild_insights"]=>
  bool(false)
  ["change_nickname"]=>
  bool(false)
  ["manage_nicknames"]=>
  bool(false)
  ["manage_emojis"]=>
  bool(false)
  ["moderate_members"]=>
  bool(false)
  ["bitwise"]=>
  string(10) "2147484672"
}

object(Discord\Parts\Permissions\RolePermission)#1870 (42) {
  ["create_instant_invite"]=>
  bool(false)
  ["manage_channels"]=>
  bool(false)
  ["view_channel"]=>
  bool(true)
  ["manage_roles"]=>
  bool(false)
  ["manage_webhooks"]=>
  bool(false)
  ["add_reactions"]=>
  bool(false)
  ["send_messages"]=>
  bool(false)
  ["send_tts_messages"]=>
  bool(false)
  ["manage_messages"]=>
  bool(false)
  ["embed_links"]=>
  bool(false)
  ["attach_files"]=>
  bool(false)
  ["read_message_history"]=>
  bool(false)
  ["mention_everyone"]=>
  bool(false)
  ["use_external_emojis"]=>
  bool(false)
  ["use_slash_commands"]=>
  bool(true)
  ["manage_threads"]=>
  bool(false)
  ["use_public_threads"]=>
  bool(false)
  ["use_private_threads"]=>
  bool(false)
  ["use_external_stickers"]=>
  bool(false)
  ["send_messages_in_threads"]=>
  bool(false)
  ["priority_speaker"]=>
  bool(false)
  ["stream"]=>
  bool(false)
  ["connect"]=>
  bool(false)
  ["speak"]=>
  bool(false)
  ["mute_members"]=>
  bool(false)
  ["deafen_members"]=>
  bool(false)
  ["move_members"]=>
  bool(false)
  ["use_vad"]=>
  bool(false)
  ["request_to_speak"]=>
  bool(false)
  ["manage_events"]=>
  bool(false)
  ["start_embedded_activities"]=>
  bool(false)
  ["kick_members"]=>
  bool(false)
  ["ban_members"]=>
  bool(false)
  ["administrator"]=>
  bool(false)
  ["manage_guild"]=>
  bool(false)
  ["view_audit_log"]=>
  bool(false)
  ["view_guild_insights"]=>
  bool(false)
  ["change_nickname"]=>
  bool(false)
  ["manage_nicknames"]=>
  bool(false)
  ["manage_emojis"]=>
  bool(false)
  ["moderate_members"]=>
  bool(false)
  ["bitwise"]=>
  string(10) "2147484672"
}
```

### CODE REVIEW

**Review by valzargaming — APPROVED** [review]

**Comment by shehi** [comment]
I strongly advise against this. It will complicate development very much. 32-bit is history, almost on all fronts. Instead of moving forward, why are we stickying ourselves to this archaic and heavily inconvenient way of development? Strings are error-prone when your data's nature is int-based and we will have a lot bugs caused by these. Just drop 32-bit support as countless other libs do and move on please? Pretty please?

**Comment by SQKo** [comment]
I'm just trying to help sir, this bug apparently also affected v6.0.0 since it uses v8 API Gateway, after 6 months release, wouldn't it be a serious issue?

So I hope this get patched with this PR as well.

Someone who have been using this library and did not notice they are facing the bug wont be happy because nobody here ever said it does not support 32 bit PHP.

https://discord.com/developers/docs/topics/permissions
The official docs explained here the permission data is serialized as string anyway:
> Permissions are stored within a variable-length integer serialized into a string, and are calculated using bitwise operations. For example, the permission value `123` will be serialized as `"123"`

And it's written to use BigInteger libraries, so I just did follow the docs:
>  we recommend deserializing the permissions using your languages' Big Integer libraries

It's only the permissions part affected, not the whole library, going to v6.0.4 just to throw error the library can't be used in 32 bit is just silly.

To be also note that Discord even send snowflake in serialized string, and this library does that, without changing it to integer, reflecting the docs. There is no one here being inconvenient with the way of the development, unless Discord did send them as 64 bit integer at first.

> And changing all those permission bits from `1 << x` to God-awful, unreadable `0xblahblah` is the worst gift we can get for the New Year! :D

No one but a techie enough would bother with readability of that bits in the source code. Bot developers are just going to use the mapped array keys as the permission names. Use `define` if that'd still bother someone, PHP is not a compiled language, just take it easy.

> P.S.: And why don't we use php-bcmath with countless years of battle testing and instead come up with this library (brick something) which doesn't even have proper v1.0?!

The library [brick/math uses 0.x.y versioning](https://github.com/brick/math#project-status--release-process) where x is the breaking change version:
> The current releases are numbered `0.x.y`. When a non-breaking change is introduced (adding new methods, optimizing existing code, etc.), `y` is incremented.

The [library also support](https://github.com/brick/math#requirements) both php-bcmath and php-gmp extension that will be automatically used.
> Although the library can work seamlessly on any PHP installation, it is highly recommended that you install the GMP or BCMath extension to speed up calculations. The fastest available calculator implementation will be automatically selected at runtime.

Now if there is someone with 32 bit php and worrying about string issue, they can just solve it by enabling GMP/BCMath extension.

Being not required to use the extension, simply means this PR is not a breaking change for a patch.

And you do not need to worry if you use php 64 bit, nothing changed due to this PR. That's why we selected that library to wrap it easy, as a hand to the 32 bit php.
All will be fine, everyone would be happy. Let me know if this patch is causing your bot a trouble.

> Just drop 32-bit support as countless other libs do and move on please? Pretty please? Just put one big exception on lib constructor to detect 32-bit and throw and be done with it. We are almost in 2022 - 64bit itself is already 2000s.

Well I'm sorry to say this personally, yes I still run 32 bit on my laptop for development (No, I run my bot at 64 bit php on production server), pardon me living in 3rd world countries. But this library helped me a lot. And I'm just trying to help it back. Otherwise I wouldn't be here from start.

Regardless this gets added or not, or otherwise drop support for 64 bit, that's fine, I can still fork this and use it personally for my development.

**Comment by shehi** [comment]
Please don't make us suffer just because you don't want to put 64bit PHP on
your local dev. Whoever is in charge of this project, should stop this PR,
get rid of 32bit support and move on. Just do major version release if
necessary, drop 32bit there.

This project barely has proper test coverage, but instead we are letting
this through. If this gets in, I personally will abandon bot development in
PHP and switch to Js. This is a mess I don't want in a serious
Discord-heavy project where permissions are extremely crucial (I am
building guildplanner.pro which runs on the back of Discord).

**Comment by shehi** [comment]
Sorry I am outside that's why posting in bits.

Few more concerns:

1. We shouldn't have multiple variable precision libraries in one lib. Use bcmath, drop anything else. Noone needs polyfill for a widely known extension.

2. This merge will complicate development, and it make readable code more complex. That's a big minus for a project which is maintained by a handful few. 

I will read your reply thoroughly in 30mins and see if I haven't answered any points there.

**Comment by valzargaming** [comment]
Thank you for the valuable feedback @shehi. To address your original concern with supporting 32-bit, DiscordPHP already does so and has for some time (see: [getSnowflakeTimestamp()](https://github.com/discord-php/DiscordPHP/blob/74fbd0efec4d66fcf4d99ac1346eb8076f0b0957/src/Discord/functions.php#L203)) and expanding its support for it only makes sense at this point.

Regarding using external libraries as dependencies to support 32-bit precision I have to concede on your opinion that it is a bit of extra work for us maintainers to make sure it works correctly on those systems, however we also acknowledge there are valid use cases where an OS may be 32-bit, particularly those that are designed to be cheap and run with a limited amount of memory available, thus we value this lib's ability to be compatible with a 32-bit PHP installation. This leaves us with 5 choices right now:
1) Use no other dependency at all, maintaining bit conversion methods ourselves within the library using methods such as with base_convert()
2) Use brick/math, which is also MIT licensed, and even the author of the library recommends just using GMP
3) Use the GMP extension (discordphp/slash already requires this so there's no issue there)
4) Update existing all existing 32-bit supported functions to default to 64-bit and require an additional dependency to process those functions if PHP_INT_SIZE === 4 during composer require, or
5) Remove all existing 32-bit support in the library and only support 64-bit, thus breaking at least a few known applications

We already have prepared working solutions for options 1 and 2. Option 3 would be the most ideal after those options are considered as we are already planning to fully integrate the slash library into dev-master in the near future. If for whatever reason we find those solutions to be insufficient or weighty on the operation of the library in a development setting we will consider option 4 as a possible solution. We will only consider option 5 as a last resort.

I hope this all makes sense to you, but if you disagree with my analysis I would love to hear your feedback and concerns so that I can bring it up in  internal discussions.

**Comment by shehi** [comment]
@valzargaming , I understand where you come from, but this situation will only make things worse, mark my words. My remarks to your comments (thank you for them) would be:

> Use no other dependency at all, maintaining bit conversion methods ourselves within the library using methods such as with base_convert()

We should stick to number-based representation as much as possible, and provide number-based values at least in comments wherever applicable, instead of outright changing them (I mean shift-values such as `1 << x` vs octal-representation nightmare which is very hard to proof-read and debug).

> Use brick/math, which is also MIT licensed, and even the author of the library recommends just using GMP
> Use the GMP extension (discordphp/slash already requires this so there's no issue there)

I absolutely don't understand why `brick/math` needs to be brought in. We can easily stick to one of `php-gmp` or `php-bcmath`. I understand at the very least we have the former already, so question is: what does `brick/math` give us that extension doesn't have? Concrete one or two examples would be great.

> Remove all existing 32-bit support in the library and only support 64-bit, thus breaking at least a few known applications

I don't think this should be last resort, but rather a planned move for a future release. BC complications aren't strange for a major version release. When we have this in mind, all code changes should be made so that all values we change here and there (from 64bit to 32bit), need to have the old 64bit notations at least in the comments, so that we could make switching fast and effectively. I know there are very few maintainers here, but this shouldn't compromise the quality of code at large. As such, I suggest we look forward into the future as well, instead of just trying to survive today :) I hope I could explain this properly, sorry if I couldn't.

> ... cases where an OS may be 32-bit, particularly those that are designed to be cheap and run with a limited amount of memory available ...

IMHO, this shouldn't be relevant to us, as DiscordPHP shouldn't be an embedded software (for IoT or similar). As such, we shouldn't care about such worries that are due to that level of resource limitation.

**Comment by shehi** [comment]
And as we refactor things, let's also write tests guys. Just for things we fix, refactor and similar.

**Comment by SQKo** [comment]
See #661

**Pull request closed without merging**
