### PR TITLE
Upgrade Carbon library

### PR DESCRIPTION
**Pull request by Korbeil**
Follow-up from https://github.com/discord-php/DiscordPHP/pull/1213

This PR is required for Symfony 7 support

### CODE REVIEW

**Review by SQKo — CHANGES_REQUESTED** [review]
Can you please add back v2? This branch minimum php version is still php8.0 not php8.1

**Comment by Korbeil** [comment]
> Can you please add back v2? This branch minimum php version is still php8.0 not php8.1

Not sure to understand what you're asking me ? You mean doing an OR ? Like `^2.38 || ^3.0` ?

**Comment by SQKo** [comment]
> > Can you please add back v2? This branch minimum php version is still php8.0 not php8.1
> 
> Not sure to understand what you're asking me ? You mean doing an OR ? Like `^2.38 || ^3.0` ?

Yes

**Comment by Korbeil** [comment]
@SQKo fixed !

**Review by valzargaming — APPROVED** [review]

**Review by SQKo — APPROVED** [review]

**Pull request merged**
